# Generated by Django 5.2.5 on 2025-08-19 07:48

import localflavor.us.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='state',
            field=localflavor.us.models.USStateField(default='NY', max_length=2),
        ),
        migrations.AddField(
            model_name='locations',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='locations',
            name='address_1',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
